/*
  ================================================================
  MEMBER DATA
  ================================================================
  This is the ONLY file you need to edit to add, remove, or update
  a member on members-templated.html. Nothing else needs to change.

  STRUCTURE OF THIS FILE
    - One flat list, window.KHK_MEMBERS_DATA, alphabetical by last
      name. There is no separate "executive board" list anywhere —
      whether someone shows up in the Executive Board section at
      the top of the page or in the regular member grid below is
      decided entirely by their `positionHeld` field, not by where
      their entry sits in this file.
    - Want to find/edit a specific exec member quickly? Search this
      file for their title in quotes, e.g. search for "President" or
      "Social Chair", and you'll land right on their entry.
    - You do NOT need to find the "right" alphabetical spot when
      adding someone new — paste their entry anywhere, even always
      at the very bottom of the list. members-templated.html sorts
      itself by id every time it loads, so the page will always show
      everyone in the correct order regardless of where they sit in
      this file. If you'd also like this file's own order tidied up
      to match (purely for your own convenience reading it), double-
      click scripts/sort-members-data.bat — entirely optional, and
      safe to run any time.

  THE 8 QUALIFYING EXEC TITLES (exact spelling/capitalization matters):
    "President", "Vice President", "Secretary", "Treasurer",
    "Social Chair", "Publicity Chair", "Academic Chair",
    "Pledge Trainer"
  If `positionHeld` is set to one of those 8 exact strings, that
  member appears ONLY in the Executive Board section (never also in
  the main grid). Anything else — including null, or some other
  title that isn't in this list — puts them in the regular grid.

  THE `status` FIELD — who's currently shown on the page:
    "active"   - shows up on the page normally. This is what every
                 current member should be set to.
    "alumni"   - graduated / permanently left. Hidden from the page,
                 but their entry (and photo/links) stays in this file
                 for the record instead of being deleted.
    "inactive" - temporarily not active (studying abroad, leave of
                 absence, etc). Hidden from the page, same as
                 "alumni" today, just tracked separately in case it's
                 ever useful to tell the two apart later.
  Only "active" members are ever shown, in either section. If a
  member's `status` is ever missing entirely, they're still treated
  as active (so a forgotten field doesn't make a new member silently
  invisible) — but that's a mistake worth fixing, and the browser
  console will flag it with an error if it happens.

  HOW TO ADD A NEW MEMBER
    1. Put their professional (composite) photo in
       assets/img/members/ named "Last, First.jpg" (comma-space,
       matches the existing photos).
    2. (Optional) put a casual photo in assets/img/members-casual/
       the same way. Skip this and leave `casualPhoto: null` and a
       neutral placeholder image is used automatically instead —
       never point casualPhoto at a different person's photo.
    3. Copy the EXAMPLE ENTRY below into the list (anywhere —
       position in the file doesn't matter, though keeping it
       alphabetical by last name makes it easier for the next
       person to scan). Fill in every field.
    4. Set `status: "active"`.
    5. For any field you don't have real info for yet, use "TBD"
       for text fields, or null for link/photo fields (linkedin,
       resume, instagram, snapchat, casualPhoto). null means "don't
       show this icon" — it will NOT render a dead/broken link.
    6. Give it a unique `id` (lowercase "last-first"; if that's
       already taken by someone else in this file, add "-2", "-3",
       etc. — a few names in this file already do this because two
       different real members happen to share a first+last name).

  HOW TO REMOVE A DEPARTING MEMBER
    Don't delete their entry — just change their `status` to
    `"alumni"` (graduated/left for good) or `"inactive"` (temporarily
    not active). That's the whole change; they'll disappear from the
    page immediately, and everything about them (photo, links, etc.)
    stays saved in case you need it later or they come back.
    If they held an exec position, it's also worth clearing
    `positionHeld` back to `null` at the same time — not required
    (the status change alone is enough to hide them everywhere), but
    it keeps the "search this file for a title in quotes" trick from
    the top of this comment pointing at whoever the role actually
    belongs to now.
    To bring someone back, just flip `status` back to `"active"`.

  EXAMPLE ENTRY:
  {
      id: "doe-jane",
      name: "Jane Doe",
      photo: "assets/img/members/Doe, Jane.jpg",
      pledgeSemester: "Spring 2026",
      positionHeld: null,               // or one of the 8 exact titles above
      status: "active",                  // "active" / "alumni" / "inactive"
      year: "Sophomore",                 // freshman / sophomore / junior / senior / graduate / post-graduate
      major: "Computer Science",
      internship: "Software Engineering Intern @ Example Corp",
      linkedin: null,                    // full URL, or null to hide the icon
      resume: null,                      // URL/path to a resume, or null to hide the icon
      casualPhoto: null,                 // path, or null to use the placeholder photo
      studentOrg: "TBD",
      blurb: "TBD",
      instagram: null,                   // full URL, or null to hide the icon
      snapchat: null                     // full URL/username, or null to hide the icon
  }

  MIGRATION NOTE (for context, not something you need to act on):
  These 63 entries were migrated from the original members.html.
  Name, photo, pledge semester, and (for the 8 current exec members)
  position were carried over as real data. Every other field below
  is brand new and didn't exist anywhere before, so it's set to
  "TBD"/null for everyone until real info is filled in.
  ================================================================
*/
window.KHK_MEMBERS_DATA = [
    {
        id: "agrawal-vidit",
        name: "Vidit Agrawal",
        photo: "assets/img/members/Agrawal, Vidit.jpg",
        pledgeSemester: "Fall 2024",
        positionHeld: null,
        status: "alumni",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "anasuri-rachith",
        name: "Rachith Anasuri",
        photo: "assets/img/members/Anasuri, Rachith.jpg",
        pledgeSemester: "Spring 2024",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "SWE @ Yahoo-Paranoid",
        linkedin: "http://www.linkedin.com/in/rachith-anasuri-369a01232",
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "bauer-kat",
        name: "Kat Bauer",
        photo: "assets/img/members/Bauer, Kat.jpg",
        pledgeSemester: "Fall 2023",
        positionHeld: "President",
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "bharadia-arnav",
        name: "Arnav Bharadia",
        photo: "assets/img/members/Bharadia, Arnav.jpg",
        pledgeSemester: "Fall 2024",
        positionHeld: null,
        status: "alumni",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "birenbaum-tanner",
        name: "Tanner Birenbaum",
        photo: "assets/img/members/Birenbaum, Tanner.jpg",
        pledgeSemester: "Spring 2024",
        positionHeld: null,
        status: "alumni",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "bowers-liliana",
        name: "Liliana Bowers",
        photo: "assets/img/members/Bowers, Liliana.jpg",
        pledgeSemester: "Fall 2023",
        positionHeld: null,
        status: "alumni",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "brophy-patrick",
        name: "Patrick Brophy",
        photo: "assets/img/members/Brophy, Patrick.jpg",
        pledgeSemester: "Fall 2024",
        positionHeld: null,
        status: "alumni",
        year: "TBD",
        major: "TBD",
        internship: "Research Software Engineer @ Morgridge Institute for Research",
        linkedin: "https://linkedin.com/in/patbrophy",
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "cerro-olivia",
        name: "Olivia Cerro",
        photo: "assets/img/members/Cerro, Olivia.jpg",
        pledgeSemester: "Spring 2026",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "chang-sean",
        name: "Sean Chang",
        photo: "assets/img/members/Chang, Sean.jpg",
        pledgeSemester: "Fall 2024",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "chou-angelina",
        name: "Angelina Chou",
        photo: "assets/img/members/Chou, Angelina.jpg",
        pledgeSemester: "Spring 2024",
        positionHeld: null,
        status: "inactive",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "conover-alex",
        name: "Alex Conover",
        photo: "assets/img/members/Conover, Alex.jpg",
        pledgeSemester: "Fall 2023",
        positionHeld: "Vice President",
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "Marketing Intern @ Keysight Technologies",
        linkedin: "http://www.linkedin.com/in/alexandra-conover-11bbb12a7",
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "cortese-michael",
        name: "Michael Cortese",
        photo: "assets/img/members/Cortese, Michael.jpg",
        pledgeSemester: "Fall 2024",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "crowe-james",
        name: "James Crowe",
        photo: "assets/img/members/Crowe, James.jpg",
        pledgeSemester: "Spring 2024",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "deviley-kate",
        name: "Kate Deviley",
        photo: "assets/img/members/Deviley, Kate.jpg",
        pledgeSemester: "Fall 2024",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "dhande-kshitij",
        name: "Kshitij Dhande",
        photo: "assets/img/members/Dhande, Kshitij.jpg",
        pledgeSemester: "Spring 2024",
        positionHeld: null,
        status: "alumni",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "diener-andrew",
        name: "Andrew Diener",
        photo: "assets/img/members/Diener, Andrew.jpg",
        pledgeSemester: "Fall 2024",
        positionHeld: null,
        status: "alumni",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "erickson-samuel",
        name: "Samuel Erickson",
        photo: "assets/img/members/Erickson, Samuel.jpg",
        pledgeSemester: "Spring 2024",
        positionHeld: null,
        status: "alumni",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "gupta-abhimanyu",
        name: "Abhimanyu Gupta",
        photo: "assets/img/members/Gupta, Abhimanyu.jpg",
        pledgeSemester: "Fall 2024",
        positionHeld: null,
        status: "alumni",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "gureno-zoe",
        name: "Zoe Gureno",
        photo: "assets/img/members/Gureno, Zoe.jpg",
        pledgeSemester: "Spring 2024",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "iadarola-vincent",
        name: "Vincent Iadarola",
        photo: "assets/img/members/Iadarola, Vincent.jpg",
        pledgeSemester: "Fall 2024",
        positionHeld: null,
        status: "alumni",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "jindal-raghav",
        name: "Raghav Jindal",
        photo: "assets/img/members/Jindal, Raghav.jpg",
        pledgeSemester: "Spring 2024",
        positionHeld: "Academic Chair",
        status: "active",
        year: "Senior",
        major: "Computer and Data Science",
        internship: "Product Engineering Intern @ Comaea Consulting",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "None",
        blurb: "I will fill in this with actual stuff later. Until then, you should join if you're on this website.",
        instagram: null,
        snapchat: null
    },
    {
        id: "jorenby-parker",
        name: "Parker Jorenby",
        photo: "assets/img/members/Jorenby, Parker.jpg",
        pledgeSemester: "Fall 2024",
        positionHeld: null,
        status: "alumni",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "kapur-karan",
        name: "Karan Kapur",
        photo: "assets/img/members/Kapur, Karan.jpg",
        pledgeSemester: "Spring 2024",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "Computer Support Assistant @ Department of Electrical and Computer Engineering, UW-Madison",
        linkedin: "https://www.linkedin.com/in/karankapur5?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "kemnitz-nicole",
        name: "Nicole Kemnitz",
        photo: "assets/img/members/Kemnitz, Nicole.jpg",
        pledgeSemester: "Fall 2024",
        positionHeld: null,
        status: "alumni",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "kerai-dhruv",
        name: "Dhruv Kerai",
        photo: "assets/img/members/Kerai, Dhruv.jpg",
        pledgeSemester: "Spring 2024",
        positionHeld: null,
        status: "alumni",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "klausner-jacob",
        name: "Jacob Klausner",
        photo: "assets/img/members/Klausner, Jacob.jpg",
        pledgeSemester: "Fall 2024",
        positionHeld: null,
        status: "alumni",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "klein-kellen",
        name: "Kellen Klein",
        photo: "assets/img/members/Klein, Kellen.jpg",
        pledgeSemester: "Spring 2024",
        positionHeld: null,
        status: "alumni",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: "https://www.linkedin.com/in/kellen-klein-77b1bb272?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "klicker-ben",
        name: "Ben Klicker",
        photo: "assets/img/members/Klicker, Ben.jpg",
        pledgeSemester: "Fall 2024",
        positionHeld: null,
        status: "alumni",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "kuhse-finn",
        name: "Finn Kuhse",
        photo: "assets/img/members/Kuhse, Finn.jpg",
        pledgeSemester: "Spring 2024",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "kujava-mckenzie",
        name: "McKenzie Kujava",
        photo: "assets/img/members/Kujava, McKenzie.jpg",
        pledgeSemester: "Fall 2024",
        positionHeld: null,
        status: "alumni",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "lamb-richard",
        name: "Richard Lamb",
        photo: "assets/img/members/Lamb, Richard.jpg",
        pledgeSemester: "Spring 2026",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "Engineering Intern @ Village of Germantown",
        linkedin: "https://www.linkedin.com/in/richard-lamb-137698386/",
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "lawry-hunter",
        name: "Hunter Lawry",
        photo: "assets/img/members/Lawry, Hunter.jpg",
        pledgeSemester: "Fall 2024",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: "http://www.linkedin.com/in/hunter-lawry-009482273",
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "leitz-katie",
        name: "Katie Leitz",
        photo: "assets/svg/crest.svg",
        pledgeSemester: "Spring 2026",
        positionHeld: "Publicity Chair",
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "malpani-rishit",
        name: "Rishit Malpani",
        photo: "assets/img/members/Malpani, Rishit.jpg",
        pledgeSemester: "Spring 2024",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "mavilla-jasmy",
        name: "Jasmy Mavilla",
        photo: "assets/img/members/Mavilla, Jasmy.jpg",
        pledgeSemester: "Fall 2024",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "IT Support Specialist @ UW School of Medicine & Public Health",
        linkedin: "https://www.linkedin.com/in/jasmymavilla000/",
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "mehrotra-dev",
        name: "Dev Mehrotra",
        photo: "assets/img/members/Mehrotra, Dev.jpg",
        pledgeSemester: "Spring 2024",
        positionHeld: null,
        status: "alumni",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "menge-kristen",
        name: "Kristen Menge",
        photo: "assets/img/members/Menge, Kristen.jpg",
        pledgeSemester: "Fall 2024",
        positionHeld: null,
        status: "alumni",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "mettu-abhay",
        name: "Abhay Mettu",
        photo: "assets/img/members/Mettu, Abhay.jpg",
        pledgeSemester: "Spring 2024",
        positionHeld: null,
        status: "alumni",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "mohammed-usman",
        name: "Usman Mohammed",
        photo: "assets/img/members/Mohammed, Usman.jpg",
        pledgeSemester: "Fall 2024",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "novak-nathan",
        name: "Nathan Novak",
        photo: "assets/img/members/Novak, Nathan.jpg",
        pledgeSemester: "Spring 2024",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "o-leary-brendan",
        name: "Brendan O'Leary",
        photo: "assets/img/members/O'Leary, Brendan.jpg",
        pledgeSemester: "Fall 2024",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "olson-scarlett",
        name: "Scarlett Olson",
        photo: "assets/img/members/Olson, Scarlett.jpg",
        pledgeSemester: "Spring 2024",
        positionHeld: null,
        status: "alumni",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "park-kevin",
        name: "Kevin Park",
        photo: "assets/img/members/Park, Kevin.jpg",
        pledgeSemester: "Spring 2026",
        positionHeld: "Treasurer",
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "patra-krishnang",
        name: "Krishnang Patra",
        photo: "assets/img/members/Patra, Krishnang.jpg",
        pledgeSemester: "Spring 2024",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "pietenpol-lexi",
        name: "Lexi Pietenpol",
        photo: "assets/img/members/Pietenpol, Lexi.jpg",
        pledgeSemester: "Fall 2024",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "race-ethan",
        name: "Ethan Race",
        photo: "assets/img/members/Race, Ethan.jpg",
        pledgeSemester: "Spring 2024",
        positionHeld: "Pledge Trainer",
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "richard-tyler",
        name: "Tyler Richard",
        photo: "assets/img/members/Richard, Tyler.jpg",
        pledgeSemester: "Fall 2024",
        positionHeld: null,
        status: "alumni",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "rollins-jack",
        name: "Jack Rollins",
        photo: "assets/img/members/Rollins, Jack.jpg",
        pledgeSemester: "Spring 2024",
        positionHeld: null,
        status: "alumni",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "sandoval-daniel",
        name: "Daniel Sandoval",
        photo: "assets/img/members/Sandoval, Daniel.jpg",
        pledgeSemester: "Fall 2024",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "schwarz-max",
        name: "Max Schwarz",
        photo: "assets/img/members/Schwarz, Max.jpg",
        pledgeSemester: "Spring 2026",
        positionHeld: null,
        status: "alumni",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "schwarz-max-2",
        name: "Max Schwarz",
        photo: "assets/img/members/Schwarz, Max.jpg",
        pledgeSemester: "Spring 2024",
        positionHeld: null,
        status: "alumni",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "skarabot-eva",
        name: "Eva Skarabot",
        photo: "assets/img/members/Skarabot, Eva.jpg",
        pledgeSemester: "Fall 2024",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: "https://www.linkedin.com/in/eva-skarabot/",
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "tabachnick-rex",
        name: "Rex Tabachnick",
        photo: "assets/img/members/Tabachnick, Rex.jpg",
        pledgeSemester: "Spring 2024",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "talluri-neha",
        name: "Neha Talluri",
        photo: "assets/img/members/Talluri, Neha.jpg",
        pledgeSemester: "Fall 2024",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "tobin-william",
        name: "William Tobin",
        photo: "assets/img/members/Tobin, William.jpg",
        pledgeSemester: "Spring 2024",
        positionHeld: null,
        status: "alumni",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "upson-brock",
        name: "Brock Upson",
        photo: "assets/img/members/Upson, Brock.jpg",
        pledgeSemester: "Fall 2024",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "woo-john",
        name: "John Woo",
        photo: "assets/img/members/Woo, John.jpg",
        pledgeSemester: "Spring 2024",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "ye-matthew",
        name: "Matthew Ye",
        photo: "assets/img/members/Ye, Matthew.jpg",
        pledgeSemester: "Spring 2026",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "young-ryan",
        name: "Ryan Young",
        photo: "assets/img/members/Young, Ryan.jpg",
        pledgeSemester: "Spring 2026",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "zimmerman-daniel",
        name: "Daniel Zimmerman",
        photo: "assets/img/members/Zimmerman, Daniel.jpg",
        pledgeSemester: "Fall 2024",
        positionHeld: null,
        status: "alumni",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "zimmerman-sheridan",
        name: "Sheridan Zimmerman",
        photo: "assets/img/members/Zimmerman, Sheridan.jpg",
        pledgeSemester: "Spring 2024",
        positionHeld: null,
        status: "alumni",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
        {
        id: "popuri-praneet",
        name: "Praneet Popuri",
        photo: "assets/svg/crest.svg",
        pledgeSemester: "TBD",
        positionHeld: "Social Chair",
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "Researcher @ Bick Lab",
        linkedin: "https://www.linkedin.com/in/praneet-popuri-6892081a2?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
        {
        id: "macdonald-owen",
        name: "Owen Macdonald",
        photo: "assets/svg/crest.svg",
        pledgeSemester: "TBD",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
        {
        id: "hahn-ryan",
        name: "Ryan Hahn",
        photo: "assets/svg/crest.svg",
        pledgeSemester: "TBD",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
        {
        id: "huhn-will",
        name: "Will Huhn",
        photo: "assets/svg/crest.svg",
        pledgeSemester: "TBD",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "House Fellow @ UW-Madison",
        linkedin: "https://www.linkedin.com/in/william-huhn-261228288/",
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
        {
        id: "kazanov-daniel",
        name: "Daniel Kazanov",
        photo: "assets/svg/crest.svg",
        pledgeSemester: "TBD",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
        {
        id: "lisle-isabella",
        name: "Isabella Lisle",
        photo: "assets/svg/crest.svg",
        pledgeSemester: "TBD",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
        {
        id: "desilver-james",
        name: "James DeSilver",
        photo: "assets/svg/crest.svg",
        pledgeSemester: "TBD",
        positionHeld: "Secretary",
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
        {
        id: "tseng-kevin",
        name: "Kevin Tseng",
        photo: "assets/svg/crest.svg",
        pledgeSemester: "TBD",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
        {
        id: "zhang-kevin",
        name: "Kevin Zhang",
        photo: "assets/svg/crest.svg",
        pledgeSemester: "TBD",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
        {
        id: "conover-logan",
        name: "Logan Conover",
        photo: "assets/svg/crest.svg",
        pledgeSemester: "TBD",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
        {
        id: "jordan-luke",
        name: "Luke Jordan",
        photo: "assets/svg/crest.svg",
        pledgeSemester: "TBD",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
        {
        id: "lin-steve",
        name: "Steve Lin",
        photo: "assets/svg/crest.svg",
        pledgeSemester: "TBD",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
        {
        id: "borse-aishwarya",
        name: "Aishwarya Borse",
        photo: "assets/svg/crest.svg",
        pledgeSemester: "TBD",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
        {
        id: "hein-amelia",
        name: "Amelia Hein",
        photo: "assets/svg/crest.svg",
        pledgeSemester: "TBD",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
        {
        id: "wendling-cecil",
        name: "Cecil Wendling",
        photo: "assets/svg/crest.svg",
        pledgeSemester: "TBD",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
        {
        id: "pecht-charlie",
        name: "Charlie Pecht",
        photo: "assets/svg/crest.svg",
        pledgeSemester: "TBD",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
        {
        id: "kaushik-neel",
        name: "Neel Kaushik",
        photo: "assets/svg/crest.svg",
        pledgeSemester: "TBD",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
        {
        id: "rashid-raza",
        name: "Raza Rashid",
        photo: "assets/svg/crest.svg",
        pledgeSemester: "TBD",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
        {
        id: "dalpe-tyler",
        name: "Tyler Dalpe",
        photo: "assets/svg/crest.svg",
        pledgeSemester: "TBD",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
    {
        id: "placeholder",
        name: "Vidit Agrawal",
        photo: "assets/img/members/Agrawal, Vidit.jpg",
        pledgeSemester: "Fall 2024",
        positionHeld: null,
        status: "active",
        year: "TBD",
        major: "TBD",
        internship: "TBD",
        linkedin: null,
        resume: null,
        casualPhoto: null,
        studentOrg: "TBD",
        blurb: "TBD",
        instagram: null,
        snapchat: null
    },
];
